language: php
php:
  - '7.1'

install:
  - composer install --prefer-dist --no-dev --optimize-autoloader --quiet

notifications:
  email:
    recipients:
      - DavidNineRoc@gmail.com
    on_success: always
    on_failure: always

script: vendor/bin/phpunit