language: php
php:
  - '7.1'

install:
  - travis_retry composer install --prefer-dist --no-dev --optimize-autoloader

notifications:
  email:
    recipients:
      - DavidNineRoc@gmail.com
    on_success: always
    on_failure: always

before_script:
  - git --version
  - php -v
  - composer --version
  - phpunit --version
  - composer install --prefer-dist --no-dev --optimize-autoloader
script:
  - vendor/bin/phpunit